<?php

/**
 * 
 * Token Compiler Class
 * Responsible for converting PHP token arrays into CSS Custom Properties (Variables)
 * and writing them to the static tokens.css file.
 */

class Core_Token_Compiler
{
    /**
     * Compile token to Css file
     * 
     * @param array $token Key-Valu pair of tokens (e.g., ['color-primary' => '#000'])
     * @return bool|int Bytes written or false on failure
     */

    public static function compile($tokens)
    {
        if (empty($tokens)) {
            return false;
        }

        $root_vars = [];
        $dark_vars = [];

        foreach ($tokens as $key => $value) {
            $clean_key = str_replace('_', '-', $key);
            $clean_value = strip_tags($value);

            // Handle Dark Mode Variables (suffix -dark)
            // e.g. color-primary-dark => --color-primary in dark scope
            if (substr($clean_key, -5) === '-dark') {
                $base_key = substr($clean_key, 0, -5);
                $dark_vars[$base_key] = $clean_value;
            } else {
                $root_vars[$clean_key] = $clean_value;
            }
        }

        $css = ":root {\n";
        foreach ($root_vars as $k => $v) {
            $css .= "    --{$k}: {$v};\n";
        }
        $css .= "}\n";

        if (!empty($dark_vars)) {
            $css .= "\n[data-theme=\"dark\"] {\n";
            foreach ($dark_vars as $k => $v) {
                $css .= "    --{$k}: {$v};\n";
            }
            $css .= "}\n";
        }

        // Add Header comment 
        $content = "/**\n * Auto-generated Token File\n * Generated by Hasht Core Token Compiler\n * Time: " . date('Y-m-d H:i:s') . "\n */\n\n" . $css;

        // Dfine path 
        $file_path = get_stylesheet_directory(  ). '/assets/css/tokens.css';

        // Create Directory is file not exists
        if (!file_exists(dirname($file_path)))
        {
             mkdir(dirname($file_path), 0755, true);
        }

        // Write to file 
        return file_put_contents($file_path, $content);
    }
}
